-- Ejecución real mes a mes (los Excel del fondo traen PROYECTADO vs REAL).
-- m01-m12 = presupuestado · r01-r12 = ejecutado.

ALTER TABLE "SalesLine" ADD COLUMN IF NOT EXISTS "r01" DECIMAL(18,2) NOT NULL DEFAULT 0;
ALTER TABLE "SalesLine" ADD COLUMN IF NOT EXISTS "r02" DECIMAL(18,2) NOT NULL DEFAULT 0;
ALTER TABLE "SalesLine" ADD COLUMN IF NOT EXISTS "r03" DECIMAL(18,2) NOT NULL DEFAULT 0;
ALTER TABLE "SalesLine" ADD COLUMN IF NOT EXISTS "r04" DECIMAL(18,2) NOT NULL DEFAULT 0;
ALTER TABLE "SalesLine" ADD COLUMN IF NOT EXISTS "r05" DECIMAL(18,2) NOT NULL DEFAULT 0;
ALTER TABLE "SalesLine" ADD COLUMN IF NOT EXISTS "r06" DECIMAL(18,2) NOT NULL DEFAULT 0;
ALTER TABLE "SalesLine" ADD COLUMN IF NOT EXISTS "r07" DECIMAL(18,2) NOT NULL DEFAULT 0;
ALTER TABLE "SalesLine" ADD COLUMN IF NOT EXISTS "r08" DECIMAL(18,2) NOT NULL DEFAULT 0;
ALTER TABLE "SalesLine" ADD COLUMN IF NOT EXISTS "r09" DECIMAL(18,2) NOT NULL DEFAULT 0;
ALTER TABLE "SalesLine" ADD COLUMN IF NOT EXISTS "r10" DECIMAL(18,2) NOT NULL DEFAULT 0;
ALTER TABLE "SalesLine" ADD COLUMN IF NOT EXISTS "r11" DECIMAL(18,2) NOT NULL DEFAULT 0;
ALTER TABLE "SalesLine" ADD COLUMN IF NOT EXISTS "r12" DECIMAL(18,2) NOT NULL DEFAULT 0;

ALTER TABLE "ExpenseLine" ADD COLUMN IF NOT EXISTS "r01" DECIMAL(18,2) NOT NULL DEFAULT 0;
ALTER TABLE "ExpenseLine" ADD COLUMN IF NOT EXISTS "r02" DECIMAL(18,2) NOT NULL DEFAULT 0;
ALTER TABLE "ExpenseLine" ADD COLUMN IF NOT EXISTS "r03" DECIMAL(18,2) NOT NULL DEFAULT 0;
ALTER TABLE "ExpenseLine" ADD COLUMN IF NOT EXISTS "r04" DECIMAL(18,2) NOT NULL DEFAULT 0;
ALTER TABLE "ExpenseLine" ADD COLUMN IF NOT EXISTS "r05" DECIMAL(18,2) NOT NULL DEFAULT 0;
ALTER TABLE "ExpenseLine" ADD COLUMN IF NOT EXISTS "r06" DECIMAL(18,2) NOT NULL DEFAULT 0;
ALTER TABLE "ExpenseLine" ADD COLUMN IF NOT EXISTS "r07" DECIMAL(18,2) NOT NULL DEFAULT 0;
ALTER TABLE "ExpenseLine" ADD COLUMN IF NOT EXISTS "r08" DECIMAL(18,2) NOT NULL DEFAULT 0;
ALTER TABLE "ExpenseLine" ADD COLUMN IF NOT EXISTS "r09" DECIMAL(18,2) NOT NULL DEFAULT 0;
ALTER TABLE "ExpenseLine" ADD COLUMN IF NOT EXISTS "r10" DECIMAL(18,2) NOT NULL DEFAULT 0;
ALTER TABLE "ExpenseLine" ADD COLUMN IF NOT EXISTS "r11" DECIMAL(18,2) NOT NULL DEFAULT 0;
ALTER TABLE "ExpenseLine" ADD COLUMN IF NOT EXISTS "r12" DECIMAL(18,2) NOT NULL DEFAULT 0;
